# Project status choices
PROJECT_STATUS_ACTIVE = 1
PROJECT_STATUS_INACTIVE = 2
PROJECT_STATUS_INITIATED = 3
PROJECT_STATUS_CLOSED = 4
PROJECT_STATUS_PROBLEM = 5

PROJECT_STATUSES = (
    (PROJECT_STATUS_ACTIVE, "ACTIVE"),
    (PROJECT_STATUS_INACTIVE, "INACTIVE"),
    (PROJECT_STATUS_INITIATED, "INITIATED"),
    (PROJECT_STATUS_CLOSED, "CLOSED"),
    (PROJECT_STATUS_PROBLEM, "PROBLEM")
)

# Sprint status choices
SPRINT_STATUS_ACTIVE = 21
SPRINT_STATUS_INACTIVE = 22
SPRINT_STATUS_STUCK = 23
SPRINT_STATUS_COMPLETE = 24

SPRINT_STATUSES = (
    (SPRINT_STATUS_ACTIVE, "ACTIVE"),
    (SPRINT_STATUS_INACTIVE, "INACTIVE"),
    (SPRINT_STATUS_STUCK, "STUCK"),
    (SPRINT_STATUS_COMPLETE, "COMPLETED")
)

# Organization Statuses
ORGANIZATION_STATUS_ACTIVE = 41
ORGANIZATION_STATUS_INACTIVE = 42

ORGANIZATION_STATUSES = (
    (ORGANIZATION_STATUS_ACTIVE, "ACTIVE"),
    (ORGANIZATION_STATUS_INACTIVE, "INACTIVE"),
)

# Designation Codes
TEAM_MEMBER = 101
TEAM_LEAD = 131
TEAM_MANAGER = 161

DESIGNATION_CHOICES = (
    (TEAM_MEMBER, "Team Member"),
    (TEAM_LEAD, "Team Lead"),
    (TEAM_MANAGER, "Team Manager")
)
