# Generated by Django 3.0.3 on 2020-02-26 16:30

import azira_bb.models.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('azira_bb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='azuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectaccess',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='azira_bb.Project'),
        ),
        migrations.CreateModel(
            name='SprintLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azira_bb.AzUser')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azira_bb.Sprint')),
            ],
            bases=(models.Model, azira_bb.models.utils.TimeStamp),
        ),
        migrations.CreateModel(
            name='ProjectLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azira_bb.AzUser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azira_bb.Project')),
            ],
            bases=(models.Model, azira_bb.models.utils.TimeStamp),
        ),
        migrations.CreateModel(
            name='IssueLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azira_bb.AzUser')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azira_bb.Issue')),
            ],
            bases=(models.Model, azira_bb.models.utils.TimeStamp),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100)),
                ('activist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azira_bb.AzUser')),
            ],
            bases=(models.Model, azira_bb.models.utils.TimeStamp),
        ),
    ]
