# Generated by Django 3.0.3 on 2020-02-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azira_bb', '0002_auto_20200226_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azuser',
            name='hobbies',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
